---
gui:
  showFileTree: false
  theme:
    activeBorderColor:
      - "#94e2d5"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#94e2d5"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

  nerdFontsVersion: "3"

git:
  parseEmoji: true
  commit:
    signOff: true

customCommands:
  - key: "l"
    context: commits
    command: git log --graph --branches --oneline
    subprocess: true
    description: "Show repository commit network"
